name: Build UsbDk

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release, Debug]
        platform: [x64, x86]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1

      - name: Install Wix Toolset
        run: |
          choco install wixtoolset --version=3.8 -y
        continue-on-error: true

      - name: Install Windows Driver Kit
        run: choco install windowsdriverkit10 -y --execution-timeout=0
        shell: pwsh


      - name: Install Windows SDK 10.1
        run: choco install windows-sdk-10.1 -y --execution-timeout=0
        shell: pwsh


      - name: Build UsbDk
        run: msbuild UsbDk.sln /p:Configuration="Win10 Release" /p:Platform=x64 /p:ValidNTTargetVersions="0x0A000000" /p:TargetVersion="0x0A000000"
        shell: pwsh
        working-directory: .
